"""
Ring Sentinel — Ring Intelligence (Explanation Layer)
========================================================
Reads the ALREADY-COMPUTED investigation result (ring_details from the
frozen v11 pipeline output) and synthesizes it into a structured,
human-readable "why was this ring flagged" report.

This layer does NOT detect fraud, does NOT touch the GraphSAGE+XGBoost
model, does NOT re-run any investigation logic, and does NOT change any
risk score or ring membership. It only reads what the detection pipeline
already decided and explains it in plain language.

DETERMINISTIC BY DESIGN — no LLM, no API key, no external network call.
Every field in the report is generated by template rules over real
aggregated evidence counts (relationship types, risk scores, exposure) —
never invented, never hallucinated. The `generated_by` field on every
report says exactly that, so this is never mistaken for an LLM output.
"""
from collections import Counter, defaultdict
import os
import json
import re
import time

REL_LABELS = {
    "shared_payout": "same payout destination",
    "referral": "a referral relationship",
    "coordinated_activity": "a synchronized claim burst",
    "proximity": "shared signup network/timing",
}
REL_DISPLAY = {
    "shared_payout": {"icon": "\U0001F4B0", "label": "Shared payout", "category": "Financial"},
    "referral": {"icon": "\U0001F517", "label": "Referral", "category": "Network"},
    "coordinated_activity": {"icon": "\u26A1", "label": "Claim burst", "category": "Temporal"},
    "proximity": {"icon": "\U0001F310", "label": "Proximity", "category": "Network"},
}
STRENGTH_RANK = {"Strong": 3, "Medium": 2, "Supporting": 1}


def build_account_blueprint(ring, account_id):
    """One account's evidence, structured — ONLY what the pipeline actually
    recorded for it. Absent evidence stays absent (null), never assumed."""
    node = next((n for n in ring["nodes"] if n["id"] == account_id), None)
    if node is None:
        return None

    my_edges = [e for e in ring["edges"] if e["from"] == account_id or e["to"] == account_id]
    relationships = []
    for e in my_edges:
        other = e["to"] if e["from"] == account_id else e["from"]
        relationships.append({"account_id": other, "relationship_type": e["type"], "strength": e["strength"]})

    evidence_types_present = sorted(set(r["relationship_type"] for r in relationships))
    evidence = {}
    type_map = {"shared_payout": "payout_convergence", "referral": "referral",
                "coordinated_activity": "claim_burst", "proximity": "proximity"}
    for rel_type, schema_key in type_map.items():
        matches = [r for r in relationships if r["relationship_type"] == rel_type]
        evidence[schema_key] = {
            "present": len(matches) > 0,
            "count": len(matches),
            "strongest": max((m["strength"] for m in matches), key=lambda s: STRENGTH_RANK.get(s, 0)) if matches else None,
        } if matches else None   # explicit None (absent), never a fabricated empty-but-present record

    return {
        "account_id": account_id,
        "risk_score": node["risk_score"],
        "final_status": "CONFIRMED",
        "evidence": evidence,
        "relationships": relationships,
        "exposure_inr": node["total_claimed"],
        "claim_count": node["claim_count"],
    }


def build_ring_blueprint(ring, blueprints):
    """Ring-level aggregation — counts and structure only, computed from
    the real per-account blueprints above."""
    rel_type_counts = Counter()
    rel_accounts_by_type = defaultdict(set)
    for e in ring["edges"]:
        rel_type_counts[e["type"]] += 1
        rel_accounts_by_type[e["type"]].add(e["from"])
        rel_accounts_by_type[e["type"]].add(e["to"])

    risk_scores = {b["account_id"]: b["risk_score"] for b in blueprints}
    evidence_type_count_per_account = {
        b["account_id"]: sum(1 for v in b["evidence"].values() if v is not None) for b in blueprints
    }

    strongest_type = max(rel_accounts_by_type, key=lambda t: len(rel_accounts_by_type[t])) if rel_accounts_by_type else None
    weakest_type = min(rel_accounts_by_type, key=lambda t: len(rel_accounts_by_type[t])) if rel_accounts_by_type else None

    # weak-evidence accounts: fewer evidence types than the ring's median, AND lower risk
    if evidence_type_count_per_account:
        counts_sorted = sorted(evidence_type_count_per_account.values())
        median_count = counts_sorted[len(counts_sorted)//2]
        weak_accounts = [aid for aid, c in evidence_type_count_per_account.items()
                          if c < median_count or (c <= 1 and risk_scores.get(aid, 1) < 0.9)]
    else:
        weak_accounts = []

    return {
        "ring_id": ring["ring_id"],
        "account_count": ring["account_count"],
        "account_ids": ring["members"],
        "risk_scores": risk_scores,
        "total_exposure_inr": ring["exposure_inr"],
        "relationship_counts_by_type": dict(rel_type_counts),
        "accounts_involved_by_type": {k: len(v) for k, v in rel_accounts_by_type.items()},
        "strongest_relationship_type": strongest_type,
        "weakest_relationship_type": weakest_type,
        "evidence_type_count_per_account": evidence_type_count_per_account,
        "weak_evidence_accounts": weak_accounts,
        "cleared_neighbor_count": len(ring.get("cleared_neighbors", [])),
    }


def _pattern_label(rel_accounts_by_type):
    categories = set()
    for rel_type in rel_accounts_by_type:
        cat = REL_DISPLAY.get(rel_type, {}).get("category")
        if cat:
            categories.add(cat)
    order = ["Financial", "Temporal", "Network"]
    ordered = [c for c in order if c in categories]
    return " + ".join(ordered) + " coordination" if ordered else "Weak/insufficient coordination signal"


def _evidence_sentences(rel_accounts_by_type, rel_type_counts):
    """Template sentences, one per relationship type present — real counts
    substituted in, nothing invented. Sorted strongest-signal-first."""
    order = ["shared_payout", "coordinated_activity", "referral", "proximity"]
    sentences = []
    for rel_type in order:
        if rel_type not in rel_accounts_by_type:
            continue
        n_accounts = len(rel_accounts_by_type[rel_type])
        n_edges = rel_type_counts[rel_type]
        desc = REL_LABELS[rel_type]
        sentences.append(f"{n_accounts} account(s) connected via {desc} ({n_edges} relationship edge(s))")
    return sentences


def generate_report(ring):
    """The full deterministic Ring Intelligence report — same structured
    schema an LLM synthesis layer would produce, generated entirely by
    template rules over real evidence. No network call, no API key."""
    blueprints = [build_account_blueprint(ring, m) for m in ring["members"]]
    blueprints = [b for b in blueprints if b is not None]
    ring_bp = build_ring_blueprint(ring, blueprints)

    rel_accounts_by_type = defaultdict(set)
    rel_type_counts = Counter()
    for e in ring["edges"]:
        rel_type_counts[e["type"]] += 1
        rel_accounts_by_type[e["type"]].add(e["from"])
        rel_accounts_by_type[e["type"]].add(e["to"])

    pattern = _pattern_label(rel_accounts_by_type)
    sentences = _evidence_sentences(rel_accounts_by_type, rel_type_counts)
    strongest_evidence = sentences[:2]
    supporting_evidence = sentences[2:]

    # per-account assessment
    account_assessments = []
    for b in blueprints:
        n_evidence = sum(1 for v in b["evidence"].values() if v is not None)
        has_strong = any(v and v.get("strongest") == "Strong" for v in b["evidence"].values() if v)
        if has_strong and b["risk_score"] >= 0.9:
            role, confidence = "Core ring member", "high"
        elif n_evidence >= 2:
            role, confidence = "Corroborated member", "high" if b["risk_score"] >= 0.75 else "medium"
        elif n_evidence == 1:
            role, confidence = "Peripheral member", "medium" if b["risk_score"] >= 0.6 else "low"
        else:
            role, confidence = "Weakly-linked member", "low"

        present_types = [rt for rt, key in [("shared_payout","payout_convergence"),("coordinated_activity","claim_burst"),
                                             ("referral","referral"),("proximity","proximity")]
                          if b["evidence"].get(key) is not None]
        evidence_summary = ", ".join(REL_LABELS[t] for t in present_types) if present_types else "no direct relationship evidence on file"

        account_assessments.append({
            "account_id": b["account_id"],
            "role_in_ring": role,
            "risk_score": b["risk_score"],
            "evidence_summary": f"Supported by {evidence_summary}." if present_types else "Supported primarily by risk score alone.",
            "confidence": confidence,
        })

    # weakest member — only reported if there's real variance (per spec: don't show unless supported)
    weakest_member = None
    if ring_bp["weak_evidence_accounts"]:
        candidates = [a for a in account_assessments if a["account_id"] in ring_bp["weak_evidence_accounts"]]
        if candidates:
            weakest = min(candidates, key=lambda a: (a["risk_score"], -len(a["evidence_summary"])))
            weakest_member = {
                "account_id": weakest["account_id"],
                "reason": f"{weakest['evidence_summary']} Risk score {weakest['risk_score']:.0%}, "
                          f"lower evidence diversity than the rest of the ring."
            }

    # evidence consistency
    all_have_evidence = all(sum(1 for v in b["evidence"].values() if v is not None) >= 1 for b in blueprints)
    all_have_strong = all(any(v and v.get("strongest") == "Strong" for v in b["evidence"].values() if v) for b in blueprints)
    if all_have_strong:
        evidence_consistency = "Every member has at least one strong, independently-verified relationship — high internal consistency."
    elif all_have_evidence:
        evidence_consistency = "Every member has at least one corroborating relationship, though strength varies across the ring."
    else:
        evidence_consistency = "Evidence strength is uneven across members — some accounts rely on weaker signals than others."

    recommended_action = "escalate" if ring["risk_label"] == "HIGH" else "watch"

    n_accounts = ring_bp["account_count"]
    top_sentence = sentences[0] if sentences else "no strong coordination signal was found"
    analyst_summary = (
        f"{n_accounts} accounts were investigated as a group. {top_sentence.capitalize()}"
        + (f", and {sentences[1]}" if len(sentences) > 1 else "")
        + f". Combined, these independent signals support the coordinated-ring hypothesis "
        + f"with {ring['confidence']:.0%} confidence. Total exposure across the group is "
        + f"\u20b9{ring_bp['total_exposure_inr']:,.0f}."
    )

    report = {
        "ring_summary": f"{n_accounts}-account cluster flagged for coordinated referral/cashback abuse.",
        "primary_pattern": pattern,
        "strongest_evidence": strongest_evidence,
        "supporting_evidence": supporting_evidence,
        "account_assessments": account_assessments,
        "weakest_member": weakest_member,
        "evidence_consistency": evidence_consistency,
        "recommended_action": recommended_action,
        "analyst_summary": analyst_summary,
        "generated_by": "deterministic_template",   # NEVER claim LLM — this is template synthesis over real counts
        "ring_blueprint": ring_bp,
        "account_blueprints": blueprints,
    }
    return report


# =======================================================================
# LLM-DRIVEN EXPLANATION (single-shot — NOT the multi-turn tool-calling
# loop that drove the investigation before). This layer never detects
# fraud, never touches risk scores or ring membership — it only receives
# the SAME blueprints generate_report() already builds above, and asks an
# LLM to synthesize the same structured schema in natural language. One
# request, one response, no tools, no multi-turn budget — a fundamentally
# simpler and more reliable shape of LLM call than the investigation loop.
# =======================================================================

LLM_AVAILABLE = False
LLM_CLIENT = None
LLM_INIT_ERROR = None
LLM_PROVIDER = None   # "groq" or "ollama" — whichever actually connected, reported honestly via /api/health

# Groq first (if GROQ_API_KEY is set) — a single-shot summarization call
# is a fundamentally easier job than the 35-tool-call agentic investigation
# loop that gave Groq's free tier trouble before (rate limits, malformed
# tool-call output). One request, modest token count, no tools — this is
# the shape of call cloud LLMs are actually reliable at. Falls back to
# Ollama (local) if no Groq key is present, then to deterministic if
# neither is reachable.
GROQ_API_KEY = os.environ.get("GROQ_API_KEY")
LLM_MODEL = os.environ.get("GROQ_MODEL", "openai/gpt-oss-20b") if GROQ_API_KEY else os.environ.get("OLLAMA_MODEL", "llama3.1")
LLM_BASE_URL = "https://api.groq.com/openai/v1" if GROQ_API_KEY else os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434/v1")

try:
    from openai import OpenAI as _OpenAIClient

    if GROQ_API_KEY:
        _candidate = _OpenAIClient(base_url=LLM_BASE_URL, api_key=GROQ_API_KEY, timeout=20.0)
        # Groq doesn't need a models.list() probe the way Ollama does (no
        # "is anything even pulled" question) — a real completion call
        # later is the actual test. Trust the key is present and proceed;
        # generate_llm_report()'s own try/except catches any real failure.
        LLM_CLIENT = _candidate
        LLM_AVAILABLE = True
        LLM_PROVIDER = "groq"
        print(f"[ring_intelligence] LLM explanation layer using Groq, model={LLM_MODEL}")
    else:
        _candidate = _OpenAIClient(base_url=LLM_BASE_URL, api_key="ollama", timeout=20.0)
        _models_resp = _candidate.models.list()
        _available = [m.id for m in _models_resp.data]
        if not _available:
            LLM_INIT_ERROR = f"Connected to Ollama at {LLM_BASE_URL} but no models are pulled."
        elif LLM_MODEL not in _available and not any(LLM_MODEL in m for m in _available):
            LLM_INIT_ERROR = f"Model '{LLM_MODEL}' not found in Ollama (available: {_available})."
        else:
            LLM_CLIENT = _candidate
            LLM_AVAILABLE = True
            LLM_PROVIDER = "ollama"
            print(f"[ring_intelligence] LLM explanation layer using Ollama (local), model={LLM_MODEL}")
except ImportError as e:
    LLM_INIT_ERROR = f"'openai' package not installed ({e})."
except Exception as e:
    LLM_INIT_ERROR = f"Could not reach {'Groq' if GROQ_API_KEY else 'Ollama'} ({type(e).__name__}: {e})."

if LLM_INIT_ERROR:
    print(f"[ring_intelligence] LLM explanation unavailable, will use deterministic synthesis — {LLM_INIT_ERROR}")


def _groq_call_with_retry(messages, max_retries=3):
    """Real retry-with-backoff for the rare transient failure — a rate
    limit or a momentary malformed-JSON generation. Single-shot calls like
    this rarely need it (unlike the old 35-turn agentic loop), but it
    costs nothing to have and means a one-off hiccup doesn't surface as a
    user-visible failure when a retry would have simply worked."""
    import re
    last_err = None
    for attempt in range(max_retries):
        try:
            return LLM_CLIENT.chat.completions.create(
                model=LLM_MODEL, messages=messages, temperature=0.1,
            ), None
        except Exception as e:
            last_err = e
            wait_s = 1.5 * (attempt + 1)
            m = re.search(r"try again in ([\d.]+)ms", str(e))
            if m:
                wait_s = max(wait_s, float(m.group(1)) / 1000.0 + 0.2)
            time.sleep(wait_s)
    return None, last_err


EXPLANATION_SYSTEM_PROMPT = """You are a fraud-analyst report writer. You are given evidence a detection
system has ALREADY computed for one investigated ring — real risk scores, real relationships, real
evidence counts. Your job is ONLY to explain this evidence in plain language. You do NOT decide whether
this is fraud, you do NOT change any risk score or membership, you do NOT invent any relationship,
transaction, motive, or fact not present in the data you are given.

Rules:
- Ground every claim in the supplied evidence. Never invent.
- Do not show chain-of-thought or private reasoning ("First I thought...", "Let me consider..."). Write
  only the final, concise, analyst-facing synthesis.
- Explain how different evidence types (payout convergence, referral, claim burst, proximity)
  reinforce each other, when they do.
- Identify the strongest and weakest ring members based on the evidence provided.
- If evidence is weak or inconsistent for any member, say so plainly — do not overstate confidence.
- The recommended_action MUST equal the "existing_verdict" field given to you — never contradict it.
- Respond with ONLY a single JSON object, no markdown fences, no prose outside the JSON, matching
  EXACTLY this schema:
{
  "ring_summary": "one sentence",
  "primary_pattern": "short label, e.g. 'Financial + Temporal coordination'",
  "strongest_evidence": ["short evidence statement", "..."],
  "supporting_evidence": ["short evidence statement", "..."],
  "account_assessments": [{"account_id": "...", "role_in_ring": "...", "evidence_summary": "...", "confidence": "high|medium|low"}],
  "weakest_member": {"account_id": "...", "reason": "..."} or null if no member is meaningfully weaker,
  "evidence_consistency": "one or two sentences",
  "recommended_action": "escalate|watch|dismiss",
  "analyst_summary": "2-4 sentence plain-language synthesis for a human analyst"
}
"""


def _extract_json(text):
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(json)?", "", text).strip()
        text = re.sub(r"```$", "", text).strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        m = re.search(r"\{.*\}", text, re.DOTALL)
        if m:
            return json.loads(m.group(0))
        raise


def generate_llm_report(ring):
    """Tries the LLM explanation first; falls back to generate_report()
    (deterministic) on ANY failure — unreachable, timeout, malformed JSON,
    missing required fields. The caller always gets a valid, schema-
    complete report either way, and `generated_by` always says truthfully
    which path produced it. Never claims LLM output when it isn't."""
    deterministic = generate_report(ring)   # always computed — doubles as the fallback AND the data source

    if not LLM_AVAILABLE:
        deterministic["llm_attempted"] = False
        deterministic["llm_status"] = LLM_INIT_ERROR or "LLM not configured"
        return deterministic

    payload = {
        "ring_id": ring["ring_id"],
        "existing_verdict": "escalate" if ring["risk_label"] == "HIGH" else "watch",
        "existing_confidence": ring["confidence"],
        "ring_blueprint": deterministic["ring_blueprint"],
        "account_blueprints": deterministic["account_blueprints"],
    }
    payload_json = json.dumps(payload, default=str)
    n_accounts = len(deterministic["account_blueprints"])
    print(f"[ring_intelligence] Sending {n_accounts} account blueprint(s) to LLM, "
          f"payload ~{len(payload_json)} bytes")

    t0 = time.time()
    try:
        resp, err = _groq_call_with_retry([
            {"role": "system", "content": EXPLANATION_SYSTEM_PROMPT},
            {"role": "user", "content": f"Evidence package for ring {ring['ring_id']}:\n{payload_json}"},
        ])
        if err is not None:
            raise err
        raw = resp.choices[0].message.content
        parsed = _extract_json(raw)

        required = ["ring_summary", "primary_pattern", "strongest_evidence", "supporting_evidence",
                     "account_assessments", "evidence_consistency", "recommended_action", "analyst_summary"]
        missing = [k for k in required if k not in parsed]
        if missing:
            raise ValueError(f"LLM response missing required field(s): {missing}")

        # Safety: recommended_action must match the existing investigation's own verdict — never let
        # the LLM override the real detection result, even if it tried to.
        parsed["recommended_action"] = payload["existing_verdict"]
        parsed.setdefault("weakest_member", None)
        parsed["generated_by"] = f"{LLM_PROVIDER}_llm:{LLM_MODEL}"
        parsed["llm_attempted"] = True
        parsed["llm_status"] = "ok"
        parsed["llm_latency_ms"] = round((time.time() - t0) * 1000, 1)
        parsed["ring_blueprint"] = deterministic["ring_blueprint"]
        parsed["account_blueprints"] = deterministic["account_blueprints"]
        print(f"[ring_intelligence] LLM explanation succeeded in {parsed['llm_latency_ms']}ms via {LLM_PROVIDER}")
        return parsed

    except Exception as e:
        print(f"[ring_intelligence] LLM explanation failed ({type(e).__name__}: {e}) — "
              f"falling back to deterministic synthesis")
        deterministic["llm_attempted"] = True
        deterministic["llm_status"] = f"LLM call failed: {type(e).__name__}: {e}"
        return deterministic
